require_relative '../../lib/rea_test/application'
require_relative '../../lib/rea_test/user_interface/main_menu'
require_relative '../../lib/rea_test/user_interface/parser'
require_relative '../../lib/rea_test/user_interface/command'
require_relative '../../lib/rea_test/user_interface/command_factory'
require_relative '../../lib/rea_test/domain/position'
require_relative '../../lib/rea_test/domain/Robot'
require_relative '../../lib/rea_test/domain/simulator'
require_relative '../../lib/rea_test/domain/table'
require_relative '../../lib/rea_test/domain/mover'
require_relative '../../lib/rea_test/domain/rotater'

require 'rspec'
